import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { DashboardService } from '../../core/services/dashboard.service';

@Component({selector:'app-access-detail',standalone:true,imports:[CommonModule],template:`
<main class="shell"><button class="back" (click)="router.navigate(['/accesos'])">← Historial de accesos</button>
<section class="hero" *ngIf="access"><div><span class="eyebrow">Detalle de seguridad</span><h1>{{ access.user || access.name || 'Registro de acceso' }}</h1><p>{{ access.email || access.document || 'Sin identificación adicional' }}</p></div><span class="status" [class.ok]="allowed">{{ allowed ? 'Acceso permitido' : 'Acceso denegado' }}</span></section>
<section class="grid" *ngIf="access"><article><span>Fecha y hora</span><strong>{{ format(access.date || access.created_at || access.createdAt) }}</strong></article><article><span>Tipo</span><strong>{{ access.type || 'Movimiento' }}</strong></article><article><span>Método</span><strong>{{ access.method || 'No reportado' }}</strong></article><article><span>Dispositivo</span><strong>{{ access.device || 'No reportado' }}</strong></article><article><span>Documento</span><strong>{{ access.document || 'No reportado' }}</strong></article><article><span>Rol</span><strong>{{ access.role || 'No reportado' }}</strong></article></section>
<section class="panel" *ngIf="access"><h2>Trazabilidad</h2><p>Identificador del registro: <strong>{{ access.id || access.access_id || 'No disponible' }}</strong></p><p>UID del usuario: <strong>{{ access.uid || 'No disponible' }}</strong></p><p>Estado reportado: <strong>{{ access.status || access.result || (allowed ? 'Permitido' : 'Denegado') }}</strong></p></section>
<section class="panel center" *ngIf="loading">Cargando detalle...</section><section class="panel center error" *ngIf="error">{{ error }}</section></main>`,styles:[`:host{display:block;min-height:100vh;background:#f4f7f5;color:#17211b;font-family:Inter,system-ui,sans-serif}.shell{max-width:1100px;margin:auto;padding:36px}.back{border:0;background:transparent;color:#00783a;font-weight:800;cursor:pointer;margin-bottom:24px}.hero,.panel,article{background:#fff;border:1px solid #dce5df;border-radius:18px;box-shadow:0 10px 30px rgba(20,55,35,.06)}.hero{padding:28px;display:flex;justify-content:space-between;align-items:center;gap:20px}.eyebrow{color:#00843d;font-weight:800;text-transform:uppercase;font-size:.78rem;letter-spacing:.1em}h1{margin:.4rem 0;font-size:2.4rem}.hero p{color:#657269}.status{padding:10px 14px;border-radius:999px;background:#fde8e8;color:#a82525;font-weight:800}.status.ok{background:#e4f6e9;color:#087332}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:18px 0}.grid article{padding:20px}.grid span{display:block;color:#6b786f;font-size:.82rem;margin-bottom:7px}.panel{padding:24px;margin-top:18px}.center{text-align:center}.error{color:#a82525}@media(max-width:760px){.shell{padding:20px}.hero{align-items:flex-start;flex-direction:column}.grid{grid-template-columns:1fr}h1{font-size:2rem}}`]})
export class AccessDetail implements OnInit { access:any=null;loading=true;error='';constructor(private route:ActivatedRoute,public router:Router,private dashboard:DashboardService){}ngOnInit(){const id=this.route.snapshot.paramMap.get('id');this.dashboard.getAccesses().subscribe({next:(res:any)=>{const list=Array.isArray(res)?res:(res?.accesses||res?.results||[]);this.access=list.find((a:any)=>String(a.id||a.access_id||a.uid)===String(id));if(!this.access)this.error='No se encontró el registro solicitado.';this.loading=false;},error:()=>{this.error='No fue posible consultar el registro.';this.loading=false;}})}get allowed(){return this.access?.allowed===true||String(this.access?.status||this.access?.result||'').toLowerCase().includes('permit')}format(v:any){if(!v)return 'Sin fecha';const d=new Date(v);return isNaN(d.getTime())?String(v):d.toLocaleString('es-CO')}}